build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.13
images:
- build_args:
  - name: max_jobs
    value: "12"
  - name: nvcc_threads
    value: "2"
  - name: TORCH_CUDA_ARCH_LIST
    value: 7.0 7.5 8.0 8.6 8.9 9.0+PTX
  - name: vllm_fa_cmake_gpu_arches
    value: 80-real;90-real
  - name: PYTHON_VERSION
    value: "3.12"
  context_dir: .
  dockerfile_path: Dockerfile.ubi
  to: vllm-build-release-cuda-rhoai-2.13
promotion:
  to:
  - namespace: red-hat-data-services
    tag: rhoai-2.13
releases:
  latest:
    release:
      architecture: amd64
      channel: stable
      version: "4.12"
resources:
  '*':
    requests:
      cpu: 200m
      memory: 200Mi
  vllm-build-release-cuda-rhoai-2.13:
    limits:
      cpu: "16"
      memory: 50Gi
    requests:
      cpu: "16"
      memory: 24Gi
tests:
- as: stable-image-mirror
  postsubmit: true
  steps:
    dependencies:
      SOURCE_IMAGE_REF: vllm-build-release-cuda-rhoai-2.13
    env:
      IMAGE_REPO: vllm
      RELEASE_VERSION: rhoai-2.13
    workflow: red-hat-data-services-ci-image-mirror
zz_generated_metadata:
  branch: rhoai-2.13
  org: red-hat-data-services
  repo: vllm
